# Proprietes de l'application
spring:
  application:
    jpa:
      hibernate:
        ddl-auto: create-drop
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
      show-sql: true
    datasource:
      url: jdbc:mysql://localhost:3306/agriconect-capteurs?serverTimezone=UTC
      username: root
      password: root
  cloud:
    # Activation remontée management dans Eureka
    config:
      service-registry:
        auto-registration:
          register-management: on

#Swagger
springdoc:
  api-docs:
    path: /api/swagger
# Configuration du log.
logging:
  level:
    org.springframework.web: INFO # Choix du niveau de log affiché
# Proprietes du serveur d'entreprise
server:
  port: 8081 # HTTP (Tomcat) port
