spring:
  application:
    name: acactionneurs
  server:
    port: 10003
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://localhost:3307/agriconnect-actionneurs?serverTimezone=UTC
    username: root
    password: root
    database-platform: org.hibernate.dialect.MySQLDialect
  doc:
    api-docs:
      path: /api/swagger

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
